### ISSUE TITLE
LifeStealSMP API

### ISSUE THREAD

**Issue by HenyPotter** [GamerDuck123/LifeStealSMP#1]
Hello! I'm a begginer programmer and I wanted to use your LifeStealAPI to make an rest API to my own server. But I don't what even that Jar file is... Am I supposed to put it into my plugins folder, or where? Thank you for response

**Comment by GamerDuck123** [comment]
Hey! So the API is installed in the main jar, the API jar sole purpose is to allow people to build off of it with a light weight jar! If you have anymore questions I can answer them faster on discord @ GamerDuck123#9999
