### ISSUE TITLE
invincible

### ISSUE THREAD

**Issue by We-arc** [GamerDuck123/LifeStealSMP#10]
when i edited my health with the command my health just froze forever

**Comment by We-arc** [comment]
i could take damage but i wouldnt kill me

**Comment by GamerDuck123** [comment]
What version are you using, and can you make a video replicating this? Are there any errors?

**Comment by NotRexil** [comment]
It's not a bug ig like when we do "/lifesteal life set (player) 9" all 10 hearts will display but the last 10th heart will only be filled half so ig he did that and he thinks that his health is frozen
