### ISSUE TITLE
Add a heart limit for withdrawing

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#11]
Add a setting to limit how much health you need to withdraw

for example on my server I only want people to withdraw extra hearts so if they had 21 hearts they can only withdraw 1 heart. and if they have 20 or less they cant withdraw at all.

**Comment by GamerDuck123** [comment]
This has been added in the most recent update: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.9-BETA 

Apologies for the late response, it was finals week this past week and I've been sick with covid
