### ISSUE TITLE
You dont gain a heart when killing someone with an end crystal

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#12]
When you kill a player with an end crystal the player doesn't gain a heart

**Comment by Animationking11** [comment]
Also, make this an option in the config because I know some servers don't want to encourage crystal PVP

**Comment by Animationking11** [comment]
Video of bug:
https://mega.nz/file/YIIFCLxR#_BF5GwbfZuCCn8ZpZbRpzlh-HtBEfJfe6ebP9XT96PA

**Comment by GamerDuck123** [comment]
This has been addressed in the most recent version!
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.0-SNAPSHOT

Apologies for the late response I have been sick and been in and out of the doctors!
