### ISSUE TITLE
Pls add this Hearts after zeroing feature

### ISSUE THREAD

**Issue by NotRexil** [GamerDuck123/LifeStealSMP#13]
Btw duck can u pls add a feature like when the player's hearts are zero and the player gets banned and after that when we unban the player and the player respawns his hearts should be 3 and configurable like add an option

Playerheartsafterzeroing = (your number) 

Pls try to add this feature and also give any eta of the feature being added and it will be good if u add it before 25th of may pls :)

**Comment by GamerDuck123** [comment]
This has been added in the most recent update: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.9-BETA 

Apologies for the late response, it was finals week this past week and I've been sick with covid
