### ISSUE TITLE
Add a max health limit

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#14]
Add a limit to how many hearts a player can have

**Comment by NotRexil** [comment]
if a killer has the max hearts and if the killer kills a player the killer wont gain a heart instead the victim would lose a heart and drop a heart which the killer can save for later

**Comment by GamerDuck123** [comment]
This has been added in the most recent update: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.9-BETA 

Apologies for the late response, it was finals week this past week and I've been sick with covid
