### ISSUE TITLE
Heal scaling

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#16]
when you have more hearts your healing scales
https://cdn.e-z.host/e-zimagehosting/98996106-718c-4250-b7d1-e6e1f6ee0b4c/b4df1269.gif

(its not because its sped up or gif lag)

**Comment by GamerDuck123** [comment]
The values were reversed i.e, false = true and true = false

This has been addressed with a quick bugfix: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.9-BUGFIX

**Comment by GamerDuck123** [comment]
Just a FYI, I uploaded the wrong jar, this has been fixed
