### ISSUE TITLE
Could not pass event PlayerDeathEvent error || Bug

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#18]
When I player is killed by a plugin "ShouldKeepLastPlayerAsDamager" value is not used and it causes and error and the player does not gain a heart

Error: https://mcpaste.io/c2a030a021327c86
Video of bug: https://mega.nz/file/8BQU1Jwb#920gPYq6JHV9P9_gYxDDMiKjTAacDECkZb1_eA7tedE
Plugin I used: https://www.spigotmc.org/resources/pvpmanager-lite.845/

**Comment by Animationking11** [comment]
Video of bug: https://mega.nz/file/8BQU1Jwb#920gPYq6JHV9P9_gYxDDMiKjTAacDECkZb1_eA7tedE

Plugin I used: https://www.spigotmc.org/resources/pvpmanager-lite.845/

**Comment by Animationking11** [comment]
Cleaner view of error https://mcpaste.io/c2a030a021327c86

**Comment by GamerDuck123** [comment]
This is currently being looked into, the problem comes with the fact they kill the player AFTER they leave, so I have to find a workaround to this, it should be added in the next version!

**Comment by GamerDuck123** [comment]
This has been fixed in the latest update!
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.2
