### ISSUE TITLE
Color Codes[suggestion]

### ISSUE THREAD

**Issue by We-arc** [GamerDuck123/LifeStealSMP#19]
i cant add a tag to this so im making a issue, anyways can you try to make it so u can add color codes to the hearts?

**Comment by GamerDuck123** [comment]
Do you mean to the health bar or the heart canaster item?

**Comment by We-arc** [comment]
heart canaster

**Comment by GamerDuck123** [comment]
This has been added in the most recent version, it also includes Hex support!

https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.0-SNAPSHOT

Apologies for the late response I have been sick and been in and out of the doctors
