### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AadiJo** [GamerDuck123/LifeStealSMP#21]
Could you eventually make the heart a custom item, or possibly implement the heart shard system to craft them? U have the best lifesteal plugin out there!

**Comment by Animationking11** [comment]
You can change what the item is in the config, on my server I changed it to red dye. If you're looking for a custom texture then you would need to force a resource pack/make a custom resource pack

**Comment by GamerDuck123** [comment]
I have added the feature to apply Custom Model Data to the heart canaster in the latest version:
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.0-SNAPSHOT

As for the using custom items for the crafting recipe, I have to do some more work on the current crafting system to do this, so that should be added next update!

Apologies for the late response I have been sick and been in and out of the doctors

**Comment by AadiJo** [comment]
alright, thanks!

**Comment by AadiJo** [comment]
If you were to implement the heart shard system, you would be the first to do so! I haven't seen anyone else do that.

**Comment by AadiJo** [comment]
> I have added the feature to apply Custom Model Data to the heart canaster in the latest version: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.0-SNAPSHOT
> 
> As for the using custom items for the crafting recipe, I have to do some more work on the current crafting system to do this, so that should be added next update!
> 
> Apologies for the late response I have been sick and been in and out of the doctors

Also, could you be more specific on how I can make a texture pack with custom model data?

**Comment by GamerDuck123** [comment]
The heart shard system is a bit harder than expected as it cannot use the default Minecraft crafting system! This most recent update has been a tiny one to add 1.19 support, the next update will definitely be heart shards with custom crafting!

As for how to make a texturepack with custom model data, I would follow a tutorial as I personally do not know how it works with the texturepack side of things, just on the code side, here's a video I found with a quick search: https://www.youtube.com/watch?v=BnKVopCtxEI

**Comment by GamerDuck123** [comment]
This feature has been added, it took a while to figure out how to do it with multiple versions, but I decided to scrape that and just make it work with 1.13+ for now, and figure something out for older versions later
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.2
