### ISSUE TITLE
Infinite heart glitch

### ISSUE THREAD

**Issue by apexfinity** [GamerDuck123/LifeStealSMP#22]
Hey there dev!
A friend and I found a bug in this plugin that allows you to obtain infinite hearts.
If you withdraw a negative amount of hearts, you will recieive a heart..
Please watch the attached video...

Thanks,
Apexfinity

https://user-images.githubusercontent.com/52583315/171744957-2cb92718-0322-4f53-8b5f-db5d7c62e5d5.mp4

**Comment by GamerDuck123** [comment]
This issue has been addressed in the latest version
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.0-SNAPSHOT

Apologies for the late response I have been sick and been in and out of the doctors
