### ISSUE TITLE
Null Withdraw Error

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#23]
Plugin version: 0.1.0-SNAPSHOT

Error: https://pastebin.com/raw/x3LHbyZE
Video of error: https://www.youtube.com/watch?v=riLgL6H5BBE

**Comment by GamerDuck123** [comment]
Oops, I forgot to mention, you need to add this to your messages.properties:
```YAML
CannotBeNegativeNumber=&cNumber can't be negative
```
