### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by callmeanidiot** [GamerDuck123/LifeStealSMP#25]
can you add something to set it so you can choose what worlds it works in as I'm making a server and one world is for lifesteal but I only need it to work in 3 worlds (lifesteal worlds)

**Comment by GamerDuck123** [comment]
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.1-SNAPSHOT

The amount of hearts wont change from world to world, but the player wont lose or gain hearts in disabled worlds in the newest release!
