### ISSUE TITLE
Please add 1.19 support

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#27]
Please I want to update my server to 1.19

**Comment by GamerDuck123** [comment]
Not much has changed so it should work on 1.19? I can push an update (with some other features Im working on) to make it native 1.19 if it doesn't

**Comment by GamerDuck123** [comment]
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.1-SNAPSHOT

The plugin is now natively using 1.19
