### ISSUE TITLE
Add Placeholders via placeholder api

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#29]
You should add some placeholders in PlaceholderAPI (https://www.spigotmc.org/resources/placeholderapi.6245/)

Some examples of some cool ones would be
%lifesteal_player_hearts% (how many hearts the player has)

I can't think of anymore right now but placeholders would be useful for things like leaderboards

**Comment by GamerDuck123** [comment]
This can now be done using %lifesteal_hearts% and using the latest update
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.1.2
