### ISSUE TITLE
If you withdraw with a full inventory you dont get the heart

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#31]
If you withdraw a heart with a full inventory the heart gets removed

Video of bug: https://s3.us-east-1.wasabisys.com/e-zimagehosting/98996106-718c-4250-b7d1-e6e1f6ee0b4c/hfxdid5n.gif

**Comment by GamerDuck123** [comment]
This will be patched in the next update

Apologies for never responding, I somehow turned off my email notifications, but they are back on now!

**Comment by GamerDuck123** [comment]
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/v0.1.4-PATCH
