### ISSUE TITLE
Combat log plugin compatibility

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#33]
How to replicate:
Get tagged in combat by hitting another player
Log out on one account
(Error shows up in chat and player dose not gain a heart)

Plugin used: https://www.spigotmc.org/resources/combatlogx.31689/
Error: https://mcpaste.io/3ba03ff412c434aa

**Comment by GamerDuck123** [comment]
This was fixed back in version 0.1.2, the most recent version is now 0.1.4: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/v0.1.4 

I'm going to leave this issue open, if the problem persists just respond here, hopefully this time I'll get an email lol
