### ISSUE TITLE
If you use a fire aspect sword and the final damage is from fire you dont get a heart

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#5]
title says it here is a recording of the bug

https://user-images.githubusercontent.com/60802108/162589948-0a2a8bf6-baed-406f-92e2-e085b8a6ef94.mp4

**Comment by GamerDuck123** [comment]
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.7-BETA
