### ISSUE TITLE
The damage scales the more hearts you have

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#7]
Video of the bug: https://mega.nz/file/QZBwUC4C#IOklYQ53EeKYgVK6NIF_objYGGDM500O2SBjYVm46Iw

**Comment by GamerDuck123** [comment]
This has been fixed in version 0.0.6-SNAPSOT https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.6-SNAPSHOT
