### ISSUE TITLE
Damage scaling is not fixed

### ISSUE THREAD

**Issue by Animationking11** [GamerDuck123/LifeStealSMP#8]
https://mega.nz/file/hIwGwRKA#O5V9vSp5sjWNhMWc_nLJFKWLx-CrqJ4BFqX6tgCtAM8

**Comment by GamerDuck123** [comment]
Sorry, there was a typo in the code, I have updated the jar on the release: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.6-SNAPSHOT 
Or optionally you can put ShouldDamageScaleWithHealth ABOVE Defaults with no indents, either way would work!

**Comment by Animationking11** [comment]
> Sorry, there was a typo in the code, I have updated the jar on the release: https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.6-SNAPSHOT Or optionally you can put ShouldDamageScaleWithHealth ABOVE Defaults with no indents, either way would work!

I tried both and it didn't work

**Comment by Animationking11** [comment]
...

**Comment by GamerDuck123** [comment]
https://github.com/GamerDuck123/LifeStealSMP/releases/tag/0.0.7-BETA
